theme = "sonokai"

[editor]
line-number = "relative"
cursorline = true
completion-trigger-len = 1
# soft-wrap.enable = true
mouse = false
idle-timeout = 0

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[keys.normal]
# sudo xbps-install -Suy xclip
y = "yank_joined_to_clipboard"
P = "paste_clipboard_before"
p = "paste_clipboard_after"
X = ["extend_line_above"]
# https://github.com/helix-editor/helix/discussions/6943
# https://github.com/helix-editor/helix/issues/3279
# https://github.com/helix-editor/helix/issues/7023
# https://stackoverflow.com/questions/71571408/multiple-tables-with-the-same-values-in-toml

[keys.select]
# sudo xbps-install -Suy xclip
y = "yank_joined_to_clipboard"
P = "paste_clipboard_before"
p = "paste_clipboard_after"
X = ["extend_line_above"]
